---
version: "3.8"
services:
  server-multitenancy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    networks:
      - app-network-multitenancy
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  db-multitenancy:
    image: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    networks:
      - app-network-multitenancy
    volumes:
      - dbdata:/var/lib/mysql
    ports:
    - "3306:3306"
  app-multitenancy:
    build: .
    restart: unless-stopped
    networks:
      - app-network-multitenancy
    volumes:
      - ./:/var/www
  node-multitenancy:
    image: node:20.4.0
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    command: sh /var/www/docker/node/node_start.sh
    depends_on:
      - app-multitenancy
networks:
  app-network-multitenancy:
    driver: bridge
volumes:
  dbdata: null
